/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowVote00 (void)
{
  GtkWidget *windowVote00;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *hseparator1;
  GtkWidget *button00confirmer;
  GtkWidget *table1;
  GtkWidget *checkbutton001;
  GtkWidget *checkbutton002;
  GtkWidget *checkbutton003;
  GtkWidget *checkbutton004;
  GtkWidget *checkbutton007;
  GtkWidget *checkbutton006;
  GtkWidget *checkbutton005;
  GtkWidget *label00vote;
  GtkWidget *label00nom;
  GtkWidget *label00ori;
  GtkWidget *label00id;
  GtkWidget *entry003;
  GtkWidget *entry0033;
  GtkWidget *entry00333;
  GtkWidget *entry03333;
  GtkWidget *entry03;
  GtkWidget *entry033;
  GtkWidget *entry002;
  GtkWidget *entry001;
  GtkWidget *entry0011;
  GtkWidget *entry0022;
  GtkWidget *entry00222;
  GtkWidget *entry0333;
  GtkWidget *entry0222;
  GtkWidget *entry022;
  GtkWidget *entry02;
  GtkWidget *entry002222;
  GtkWidget *entry00111;
  GtkWidget *entry001111;
  GtkWidget *entry01;
  GtkWidget *entry011;
  GtkWidget *entry0111;
  GtkWidget *entry03333;
  GtkWidget *entry02222;
  GtkWidget *entry01111;
  GtkWidget *checkbutton008;
  GtkWidget *image2;
  GtkWidget *button00annuler;
  GtkWidget *image1;
  GtkWidget *image3;

  windowVote00 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowVote00), _("Menu de Vote"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowVote00), fixed1);
  gtk_container_set_border_width (GTK_CONTAINER (fixed1), 4);
  gtk_widget_set_sensitive (fixed1, FALSE);

  label1 = gtk_label_new (_("Menu Vote"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 824, 32);
  gtk_widget_set_size_request (label1, 227, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 24, 80);
  gtk_widget_set_size_request (hseparator1, 1824, 16);
  gtk_widget_set_sensitive (hseparator1, FALSE);

  button00confirmer = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (button00confirmer);
  gtk_fixed_put (GTK_FIXED (fixed1), button00confirmer, 984, 670);
  gtk_widget_set_size_request (button00confirmer, 111, 40);

  table1 = gtk_table_new (9, 4, TRUE);
  gtk_widget_show (table1);
  gtk_fixed_put (GTK_FIXED (fixed1), table1, 688, 128);
  gtk_widget_set_size_request (table1, 556, 492);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 21);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 3);

  checkbutton001 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton001);
  gtk_table_attach (GTK_TABLE (table1), checkbutton001, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton002 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton002);
  gtk_table_attach (GTK_TABLE (table1), checkbutton002, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton003 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton003);
  gtk_table_attach (GTK_TABLE (table1), checkbutton003, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton004 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton004);
  gtk_table_attach (GTK_TABLE (table1), checkbutton004, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton007 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton007);
  gtk_table_attach (GTK_TABLE (table1), checkbutton007, 3, 4, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton006 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton006);
  gtk_table_attach (GTK_TABLE (table1), checkbutton006, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton005 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton005);
  gtk_table_attach (GTK_TABLE (table1), checkbutton005, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label00vote = gtk_label_new ("");
  gtk_widget_show (label00vote);
  gtk_table_attach (GTK_TABLE (table1), label00vote, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label00vote), 0, 0.5);

  label00nom = gtk_label_new (_("Nom de la liste"));
  gtk_widget_show (label00nom);
  gtk_table_attach (GTK_TABLE (table1), label00nom, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label00nom), 0, 0.5);

  label00ori = gtk_label_new (_("Orientation"));
  gtk_widget_show (label00ori);
  gtk_table_attach (GTK_TABLE (table1), label00ori, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label00ori), 0, 0.5);

  label00id = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label00id);
  gtk_table_attach (GTK_TABLE (table1), label00id, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label00id), 0, 0.5);

  entry003 = gtk_entry_new ();
  gtk_widget_show (entry003);
  gtk_table_attach (GTK_TABLE (table1), entry003, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry003), 8226);

  entry0033 = gtk_entry_new ();
  gtk_widget_show (entry0033);
  gtk_table_attach (GTK_TABLE (table1), entry0033, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0033), 8226);

  entry00333 = gtk_entry_new ();
  gtk_widget_show (entry00333);
  gtk_table_attach (GTK_TABLE (table1), entry00333, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00333), 8226);

  entry03333 = gtk_entry_new ();
  gtk_widget_show (entry03333);
  gtk_table_attach (GTK_TABLE (table1), entry03333, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry03333), 8226);

  entry03 = gtk_entry_new ();
  gtk_widget_show (entry03);
  gtk_table_attach (GTK_TABLE (table1), entry03, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry03), 8226);

  entry033 = gtk_entry_new ();
  gtk_widget_show (entry033);
  gtk_table_attach (GTK_TABLE (table1), entry033, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry033), 8226);

  entry002 = gtk_entry_new ();
  gtk_widget_show (entry002);
  gtk_table_attach (GTK_TABLE (table1), entry002, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry002), 8226);

  entry001 = gtk_entry_new ();
  gtk_widget_show (entry001);
  gtk_table_attach (GTK_TABLE (table1), entry001, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry001), 8226);

  entry0011 = gtk_entry_new ();
  gtk_widget_show (entry0011);
  gtk_table_attach (GTK_TABLE (table1), entry0011, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0011), 8226);

  entry0022 = gtk_entry_new ();
  gtk_widget_show (entry0022);
  gtk_table_attach (GTK_TABLE (table1), entry0022, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0022), 8226);

  entry00222 = gtk_entry_new ();
  gtk_widget_show (entry00222);
  gtk_table_attach (GTK_TABLE (table1), entry00222, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00222), 8226);

  entry0333 = gtk_entry_new ();
  gtk_widget_show (entry0333);
  gtk_table_attach (GTK_TABLE (table1), entry0333, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0333), 8226);

  entry0222 = gtk_entry_new ();
  gtk_widget_show (entry0222);
  gtk_table_attach (GTK_TABLE (table1), entry0222, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0222), 8226);

  entry022 = gtk_entry_new ();
  gtk_widget_show (entry022);
  gtk_table_attach (GTK_TABLE (table1), entry022, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry022), 8226);

  entry02 = gtk_entry_new ();
  gtk_widget_show (entry02);
  gtk_table_attach (GTK_TABLE (table1), entry02, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry02), 8226);

  entry002222 = gtk_entry_new ();
  gtk_widget_show (entry002222);
  gtk_table_attach (GTK_TABLE (table1), entry002222, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry002222), 8226);

  entry00111 = gtk_entry_new ();
  gtk_widget_show (entry00111);
  gtk_table_attach (GTK_TABLE (table1), entry00111, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00111), 8226);

  entry001111 = gtk_entry_new ();
  gtk_widget_show (entry001111);
  gtk_table_attach (GTK_TABLE (table1), entry001111, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry001111), 8226);

  entry01 = gtk_entry_new ();
  gtk_widget_show (entry01);
  gtk_table_attach (GTK_TABLE (table1), entry01, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry01), 8226);

  entry011 = gtk_entry_new ();
  gtk_widget_show (entry011);
  gtk_table_attach (GTK_TABLE (table1), entry011, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry011), 8226);

  entry0111 = gtk_entry_new ();
  gtk_widget_show (entry0111);
  gtk_table_attach (GTK_TABLE (table1), entry0111, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry0111), 8226);

  entry03333 = gtk_entry_new ();
  gtk_widget_show (entry03333);
  gtk_table_attach (GTK_TABLE (table1), entry03333, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry03333), 8226);

  entry02222 = gtk_entry_new ();
  gtk_widget_show (entry02222);
  gtk_table_attach (GTK_TABLE (table1), entry02222, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry02222), 8226);

  entry01111 = gtk_entry_new ();
  gtk_widget_show (entry01111);
  gtk_table_attach (GTK_TABLE (table1), entry01111, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry01111), 8226);

  checkbutton008 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton008);
  gtk_table_attach (GTK_TABLE (table1), checkbutton008, 3, 4, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 976, 672);
  gtk_widget_set_size_request (image2, 44, 33);

  button00annuler = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button00annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), button00annuler, 840, 670);
  gtk_widget_set_size_request (button00annuler, 111, 40);

  image1 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 816, 648);
  gtk_widget_set_size_request (image1, 80, 84);
  gtk_widget_set_sensitive (image1, FALSE);

  image3 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 848, 16);
  gtk_widget_set_size_request (image3, 84, 60);

  g_signal_connect ((gpointer) fixed1, "toggled",
                    G_CALLBACK (on_fixed1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button00confirmer, "clicked",
                    G_CALLBACK (on_button00confirmer_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton002, "toggled",
                    G_CALLBACK (on_checkbutton002_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton003, "toggled",
                    G_CALLBACK (on_checkbutton003_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton004, "toggled",
                    G_CALLBACK (on_checkbutton004_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton007, "toggled",
                    G_CALLBACK (on_checkbutton007_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton006, "toggled",
                    G_CALLBACK (on_checkbutton006_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton005, "toggled",
                    G_CALLBACK (on_checkbutton005_toggled),
                    NULL);
  g_signal_connect ((gpointer) entry0033, "changed",
                    G_CALLBACK (on_entry0033_changed),
                    NULL);
  g_signal_connect ((gpointer) entry03, "changed",
                    G_CALLBACK (on_entry03_changed),
                    NULL);
  g_signal_connect ((gpointer) entry033, "changed",
                    G_CALLBACK (on_entry033_changed),
                    NULL);
  g_signal_connect ((gpointer) entry002, "changed",
                    G_CALLBACK (on_entry002_changed),
                    NULL);
  g_signal_connect ((gpointer) entry001, "changed",
                    G_CALLBACK (on_entry001_changed),
                    NULL);
  g_signal_connect ((gpointer) entry0011, "changed",
                    G_CALLBACK (on_entry0011_changed),
                    NULL);
  g_signal_connect ((gpointer) entry0022, "changed",
                    G_CALLBACK (on_entry0022_changed),
                    NULL);
  g_signal_connect ((gpointer) entry00222, "changed",
                    G_CALLBACK (on_entry00222_changed),
                    NULL);
  g_signal_connect ((gpointer) entry022, "changed",
                    G_CALLBACK (on_entry022_changed),
                    NULL);
  g_signal_connect ((gpointer) entry02, "changed",
                    G_CALLBACK (on_entry02_changed),
                    NULL);
  g_signal_connect ((gpointer) entry002222, "changed",
                    G_CALLBACK (on_entry002222_changed),
                    NULL);
  g_signal_connect ((gpointer) entry00111, "changed",
                    G_CALLBACK (on_entry00111_changed),
                    NULL);
  g_signal_connect ((gpointer) entry001111, "changed",
                    G_CALLBACK (on_entry001111_changed),
                    NULL);
  g_signal_connect ((gpointer) entry01, "changed",
                    G_CALLBACK (on_entry01_changed),
                    NULL);
  g_signal_connect ((gpointer) entry011, "changed",
                    G_CALLBACK (on_entry011_changed),
                    NULL);
  g_signal_connect ((gpointer) entry0111, "changed",
                    G_CALLBACK (on_entry0111_changed),
                    NULL);
  g_signal_connect ((gpointer) entry03333, "changed",
                    G_CALLBACK (on_entry03333_changed),
                    NULL);
  g_signal_connect ((gpointer) entry02222, "changed",
                    G_CALLBACK (on_entry02222_changed),
                    NULL);
  g_signal_connect ((gpointer) checkbutton008, "toggled",
                    G_CALLBACK (on_checkbutton008_toggled),
                    NULL);
  g_signal_connect ((gpointer) button00annuler, "clicked",
                    G_CALLBACK (on_button00annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowVote00, windowVote00, "windowVote00");
  GLADE_HOOKUP_OBJECT (windowVote00, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowVote00, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowVote00, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (windowVote00, button00confirmer, "button00confirmer");
  GLADE_HOOKUP_OBJECT (windowVote00, table1, "table1");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton001, "checkbutton001");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton002, "checkbutton002");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton003, "checkbutton003");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton004, "checkbutton004");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton007, "checkbutton007");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton006, "checkbutton006");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton005, "checkbutton005");
  GLADE_HOOKUP_OBJECT (windowVote00, label00vote, "label00vote");
  GLADE_HOOKUP_OBJECT (windowVote00, label00nom, "label00nom");
  GLADE_HOOKUP_OBJECT (windowVote00, label00ori, "label00ori");
  GLADE_HOOKUP_OBJECT (windowVote00, label00id, "label00id");
  GLADE_HOOKUP_OBJECT (windowVote00, entry003, "entry003");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0033, "entry0033");
  GLADE_HOOKUP_OBJECT (windowVote00, entry00333, "entry00333");
  GLADE_HOOKUP_OBJECT (windowVote00, entry03333, "entry03333");
  GLADE_HOOKUP_OBJECT (windowVote00, entry03, "entry03");
  GLADE_HOOKUP_OBJECT (windowVote00, entry033, "entry033");
  GLADE_HOOKUP_OBJECT (windowVote00, entry002, "entry002");
  GLADE_HOOKUP_OBJECT (windowVote00, entry001, "entry001");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0011, "entry0011");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0022, "entry0022");
  GLADE_HOOKUP_OBJECT (windowVote00, entry00222, "entry00222");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0333, "entry0333");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0222, "entry0222");
  GLADE_HOOKUP_OBJECT (windowVote00, entry022, "entry022");
  GLADE_HOOKUP_OBJECT (windowVote00, entry02, "entry02");
  GLADE_HOOKUP_OBJECT (windowVote00, entry002222, "entry002222");
  GLADE_HOOKUP_OBJECT (windowVote00, entry00111, "entry00111");
  GLADE_HOOKUP_OBJECT (windowVote00, entry001111, "entry001111");
  GLADE_HOOKUP_OBJECT (windowVote00, entry01, "entry01");
  GLADE_HOOKUP_OBJECT (windowVote00, entry011, "entry011");
  GLADE_HOOKUP_OBJECT (windowVote00, entry0111, "entry0111");
  GLADE_HOOKUP_OBJECT (windowVote00, entry03333, "entry03333");
  GLADE_HOOKUP_OBJECT (windowVote00, entry02222, "entry02222");
  GLADE_HOOKUP_OBJECT (windowVote00, entry01111, "entry01111");
  GLADE_HOOKUP_OBJECT (windowVote00, checkbutton008, "checkbutton008");
  GLADE_HOOKUP_OBJECT (windowVote00, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowVote00, button00annuler, "button00annuler");
  GLADE_HOOKUP_OBJECT (windowVote00, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowVote00, image3, "image3");

  return windowVote00;
}

GtkWidget*
create_windowAjout (void)
{
  GtkWidget *windowAjout;
  GtkWidget *fixed2;
  GtkWidget *entry00nomliste;
  GtkWidget *entry00nomtete;
  GtkWidget *entry00iditete;
  GtkWidget *entry00ide;
  GtkWidget *radiobutton00gauche;
  GSList *radiobutton00gauche_group = NULL;
  GtkWidget *radiobutton00centre;
  GtkWidget *radiobutton00droite;
  GtkWidget *label00idtete;
  GtkWidget *label00candid;
  GtkWidget *label00nomliste;
  GtkWidget *Orientatio00;
  GtkWidget *label00identifiant;
  GtkWidget *label00nontete;
  GtkWidget *clist1;
  GtkWidget *label00nomcand;
  GtkWidget *label00prenomcand;
  GtkWidget *label00;
  GtkWidget *butto00Annuler;
  GtkWidget *label00Ajouteruneliste;
  GtkWidget *button00confirmer;

  windowAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowAjout), _("Menu d'Ajout"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowAjout), fixed2);

  entry00nomliste = gtk_entry_new ();
  gtk_widget_show (entry00nomliste);
  gtk_fixed_put (GTK_FIXED (fixed2), entry00nomliste, 360, 152);
  gtk_widget_set_size_request (entry00nomliste, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00nomliste), 8226);

  entry00nomtete = gtk_entry_new ();
  gtk_widget_show (entry00nomtete);
  gtk_fixed_put (GTK_FIXED (fixed2), entry00nomtete, 344, 384);
  gtk_widget_set_size_request (entry00nomtete, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00nomtete), 8226);

  entry00iditete = gtk_entry_new ();
  gtk_widget_show (entry00iditete);
  gtk_fixed_put (GTK_FIXED (fixed2), entry00iditete, 344, 440);
  gtk_widget_set_size_request (entry00iditete, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00iditete), 8226);

  entry00ide = gtk_entry_new ();
  gtk_widget_show (entry00ide);
  gtk_fixed_put (GTK_FIXED (fixed2), entry00ide, 296, 200);
  gtk_widget_set_size_request (entry00ide, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00ide), 8226);

  radiobutton00gauche = gtk_radio_button_new_with_mnemonic (NULL, _("Gauche"));
  gtk_widget_show (radiobutton00gauche);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton00gauche, 288, 296);
  gtk_widget_set_size_request (radiobutton00gauche, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton00gauche), radiobutton00gauche_group);
  radiobutton00gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton00gauche));

  radiobutton00centre = gtk_radio_button_new_with_mnemonic (NULL, _("Centre"));
  gtk_widget_show (radiobutton00centre);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton00centre, 440, 296);
  gtk_widget_set_size_request (radiobutton00centre, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton00centre), radiobutton00gauche_group);
  radiobutton00gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton00centre));

  radiobutton00droite = gtk_radio_button_new_with_mnemonic (NULL, _("Droite"));
  gtk_widget_show (radiobutton00droite);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton00droite, 608, 296);
  gtk_widget_set_size_request (radiobutton00droite, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton00droite), radiobutton00gauche_group);
  radiobutton00gauche_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton00droite));

  label00idtete = gtk_label_new (_("Id tete liste :"));
  gtk_widget_show (label00idtete);
  gtk_fixed_put (GTK_FIXED (fixed2), label00idtete, 216, 448);
  gtk_widget_set_size_request (label00idtete, 101, 17);

  label00candid = gtk_label_new (_("Candidats :"));
  gtk_widget_show (label00candid);
  gtk_fixed_put (GTK_FIXED (fixed2), label00candid, 200, 528);
  gtk_widget_set_size_request (label00candid, 126, 17);

  label00nomliste = gtk_label_new (_("Nom de la liste : "));
  gtk_widget_show (label00nomliste);
  gtk_fixed_put (GTK_FIXED (fixed2), label00nomliste, 192, 160);
  gtk_widget_set_size_request (label00nomliste, 120, 17);

  Orientatio00 = gtk_label_new (_("Orientation : "));
  gtk_widget_show (Orientatio00);
  gtk_fixed_put (GTK_FIXED (fixed2), Orientatio00, 176, 264);
  gtk_widget_set_size_request (Orientatio00, 141, 17);

  label00identifiant = gtk_label_new (_("Identifiant : "));
  gtk_widget_show (label00identifiant);
  gtk_fixed_put (GTK_FIXED (fixed2), label00identifiant, 208, 208);
  gtk_widget_set_size_request (label00identifiant, 83, 17);

  label00nontete = gtk_label_new (_("Nom et pr\303\251nom\n tete liste :"));
  gtk_widget_show (label00nontete);
  gtk_fixed_put (GTK_FIXED (fixed2), label00nontete, 200, 384);
  gtk_widget_set_size_request (label00nontete, 141, 30);

  clist1 = gtk_clist_new (3);
  gtk_widget_show (clist1);
  gtk_fixed_put (GTK_FIXED (fixed2), clist1, 320, 568);
  gtk_widget_set_size_request (clist1, 472, 144);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 128);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 152);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label00nomcand = gtk_label_new (_("Nom"));
  gtk_widget_show (label00nomcand);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label00nomcand);

  label00prenomcand = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label00prenomcand);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label00prenomcand);

  label00 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label00);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label00);

  butto00Annuler = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (butto00Annuler);
  gtk_fixed_put (GTK_FIXED (fixed2), butto00Annuler, 280, 784);
  gtk_widget_set_size_request (butto00Annuler, 216, 45);

  label00Ajouteruneliste = gtk_label_new (_("Ajouter une liste \303\251lectorale"));
  gtk_widget_show (label00Ajouteruneliste);
  gtk_fixed_put (GTK_FIXED (fixed2), label00Ajouteruneliste, 776, 16);
  gtk_widget_set_size_request (label00Ajouteruneliste, 314, 47);

  button00confirmer = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (button00confirmer);
  gtk_fixed_put (GTK_FIXED (fixed2), button00confirmer, 536, 784);
  gtk_widget_set_size_request (button00confirmer, 216, 45);

  g_signal_connect ((gpointer) entry00nomliste, "changed",
                    G_CALLBACK (on_entry25_changed),
                    NULL);
  g_signal_connect ((gpointer) clist1, "abort_column_resize",
                    G_CALLBACK (on_clist1_click_column),
                    NULL);
  g_signal_connect ((gpointer) button00confirmer, "clicked",
                    G_CALLBACK (on_button00confirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowAjout, windowAjout, "windowAjout");
  GLADE_HOOKUP_OBJECT (windowAjout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowAjout, entry00nomliste, "entry00nomliste");
  GLADE_HOOKUP_OBJECT (windowAjout, entry00nomtete, "entry00nomtete");
  GLADE_HOOKUP_OBJECT (windowAjout, entry00iditete, "entry00iditete");
  GLADE_HOOKUP_OBJECT (windowAjout, entry00ide, "entry00ide");
  GLADE_HOOKUP_OBJECT (windowAjout, radiobutton00gauche, "radiobutton00gauche");
  GLADE_HOOKUP_OBJECT (windowAjout, radiobutton00centre, "radiobutton00centre");
  GLADE_HOOKUP_OBJECT (windowAjout, radiobutton00droite, "radiobutton00droite");
  GLADE_HOOKUP_OBJECT (windowAjout, label00idtete, "label00idtete");
  GLADE_HOOKUP_OBJECT (windowAjout, label00candid, "label00candid");
  GLADE_HOOKUP_OBJECT (windowAjout, label00nomliste, "label00nomliste");
  GLADE_HOOKUP_OBJECT (windowAjout, Orientatio00, "Orientatio00");
  GLADE_HOOKUP_OBJECT (windowAjout, label00identifiant, "label00identifiant");
  GLADE_HOOKUP_OBJECT (windowAjout, label00nontete, "label00nontete");
  GLADE_HOOKUP_OBJECT (windowAjout, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (windowAjout, label00nomcand, "label00nomcand");
  GLADE_HOOKUP_OBJECT (windowAjout, label00prenomcand, "label00prenomcand");
  GLADE_HOOKUP_OBJECT (windowAjout, label00, "label00");
  GLADE_HOOKUP_OBJECT (windowAjout, butto00Annuler, "butto00Annuler");
  GLADE_HOOKUP_OBJECT (windowAjout, label00Ajouteruneliste, "label00Ajouteruneliste");
  GLADE_HOOKUP_OBJECT (windowAjout, button00confirmer, "button00confirmer");

  return windowAjout;
}

GtkWidget*
create_window00affichage (void)
{
  GtkWidget *window00affichage;
  GtkWidget *fixed3;
  GtkWidget *entry00recherche;
  GtkWidget *clist2;
  GtkWidget *label00id;
  GtkWidget *label45;
  GtkWidget *label00orientation_;
  GtkWidget *label00recher;
  GtkWidget *button00recherche;
  GtkWidget *image00recher;
  GtkWidget *label00afficher;
  GtkWidget *button00Supp;
  GtkWidget *button00modifier;
  GtkWidget *button00annuler;
  GtkWidget *button00confirmer;
  GtkWidget *button00Menueprinc;

  window00affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window00affichage), _("Afficher une liste "));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window00affichage), fixed3);

  entry00recherche = gtk_entry_new ();
  gtk_widget_show (entry00recherche);
  gtk_fixed_put (GTK_FIXED (fixed3), entry00recherche, 1416, 64);
  gtk_widget_set_size_request (entry00recherche, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry00recherche), 8226);

  clist2 = gtk_clist_new (4);
  gtk_widget_show (clist2);
  gtk_fixed_put (GTK_FIXED (fixed3), clist2, 592, 120);
  gtk_widget_set_size_request (clist2, 680, 448);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 130);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 216);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 451);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 298);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  label00id = gtk_label_new (_("Id"));
  gtk_widget_show (label00id);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label00id);

  label45 = gtk_label_new (_("Nom liste "));
  gtk_widget_show (label45);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, label45);

  label00orientation_ = gtk_label_new (_("Orientation "));
  gtk_widget_show (label00orientation_);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, label00orientation_);

  label00recher = gtk_label_new (_("Rechercher :"));
  gtk_widget_show (label00recher);
  gtk_fixed_put (GTK_FIXED (fixed3), label00recher, 1312, 72);
  gtk_widget_set_size_request (label00recher, 85, 17);

  button00recherche = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (button00recherche);
  gtk_fixed_put (GTK_FIXED (fixed3), button00recherche, 1600, 64);
  gtk_widget_set_size_request (button00recherche, 40, 32);

  image00recher = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image00recher);
  gtk_fixed_put (GTK_FIXED (fixed3), image00recher, 1600, 64);
  gtk_widget_set_size_request (image00recher, 40, 29);

  label00afficher = gtk_label_new (_("Afficher les listes \303\251lectorales :"));
  gtk_widget_show (label00afficher);
  gtk_fixed_put (GTK_FIXED (fixed3), label00afficher, 800, 32);
  gtk_widget_set_size_request (label00afficher, 264, 16);

  button00Supp = gtk_button_new_with_mnemonic (_("Supprimer une liste "));
  gtk_widget_show (button00Supp);
  gtk_fixed_put (GTK_FIXED (fixed3), button00Supp, 792, 656);
  gtk_widget_set_size_request (button00Supp, 256, 53);

  button00modifier = gtk_button_new_with_mnemonic (_("Modifier une liste "));
  gtk_widget_show (button00modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button00modifier, 792, 592);
  gtk_widget_set_size_request (button00modifier, 256, 53);

  button00annuler = gtk_button_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (button00annuler);
  gtk_fixed_put (GTK_FIXED (fixed3), button00annuler, 736, 808);
  gtk_widget_set_size_request (button00annuler, 128, 37);

  button00confirmer = gtk_button_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (button00confirmer);
  gtk_fixed_put (GTK_FIXED (fixed3), button00confirmer, 936, 808);
  gtk_widget_set_size_request (button00confirmer, 128, 37);

  button00Menueprinc = gtk_button_new_with_mnemonic (_("Menu Principale "));
  gtk_widget_show (button00Menueprinc);
  gtk_fixed_put (GTK_FIXED (fixed3), button00Menueprinc, 48, 40);
  gtk_widget_set_size_request (button00Menueprinc, 160, 40);

  g_signal_connect ((gpointer) button00recherche, "enter",
                    G_CALLBACK (on_button00recherche_enter),
                    NULL);
  g_signal_connect ((gpointer) button00Supp, "clicked",
                    G_CALLBACK (on_button00Supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button00modifier, "clicked",
                    G_CALLBACK (on_button00modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button00Menueprinc, "leave",
                    G_CALLBACK (on_button00Menueprinc_leave),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window00affichage, window00affichage, "window00affichage");
  GLADE_HOOKUP_OBJECT (window00affichage, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window00affichage, entry00recherche, "entry00recherche");
  GLADE_HOOKUP_OBJECT (window00affichage, clist2, "clist2");
  GLADE_HOOKUP_OBJECT (window00affichage, label00id, "label00id");
  GLADE_HOOKUP_OBJECT (window00affichage, label45, "label45");
  GLADE_HOOKUP_OBJECT (window00affichage, label00orientation_, "label00orientation_");
  GLADE_HOOKUP_OBJECT (window00affichage, label00recher, "label00recher");
  GLADE_HOOKUP_OBJECT (window00affichage, button00recherche, "button00recherche");
  GLADE_HOOKUP_OBJECT (window00affichage, image00recher, "image00recher");
  GLADE_HOOKUP_OBJECT (window00affichage, label00afficher, "label00afficher");
  GLADE_HOOKUP_OBJECT (window00affichage, button00Supp, "button00Supp");
  GLADE_HOOKUP_OBJECT (window00affichage, button00modifier, "button00modifier");
  GLADE_HOOKUP_OBJECT (window00affichage, button00annuler, "button00annuler");
  GLADE_HOOKUP_OBJECT (window00affichage, button00confirmer, "button00confirmer");
  GLADE_HOOKUP_OBJECT (window00affichage, button00Menueprinc, "button00Menueprinc");

  return window00affichage;
}

